services:
  postgres:
    image: postgres:17
    container_name: bloom-postgres
    environment:
      POSTGRES_DB: bloom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
